// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Table = require("envio/src/db/Table.bs.js");
let Utils = require("envio/src/Utils.bs.js");
let Schema = require("envio/src/db/Schema.bs.js");
let Stdlib_Promise = require("@rescript/runtime/lib/js/Stdlib_Promise.js");

function touch_all() {
  Stdlib_Promise.$$catch();
  Promise.resolve();
  Schema.getDerivedFromFieldName();
  Table.getCompositeIndices();
  Table.getDbFieldName();
  Table.getDerivedFromFields();
  Table.getFields();
  Table.getPrimaryKeyFieldNames();
  Table.getSingleIndices();
  Utils.unwrapResultExn();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
