// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Throttler = require("envio/src/Throttler.bs.js");

function touch_all() {
  Throttler.make();
  Throttler.schedule();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
