// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Rest = require("envio/src/vendored/Rest.bs.js");
let Viem = require("envio/src/bindings/Viem.bs.js");
let LogSelection = require("envio/src/LogSelection.bs.js");
let HyperSyncClient = require("envio/src/sources/HyperSyncClient.bs.js");
let HyperSyncJsonApi = require("envio/src/sources/HyperSyncJsonApi.bs.js");

function touch_all() {
  HyperSyncClient.make();
  HyperSyncJsonApi.heightRoute();
  LogSelection.make();
  Promise.resolve();
  Rest.client();
  Rest.fetch();
  Viem.parseLogOrThrow();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
