// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let EntityHistory = require("envio/src/db/EntityHistory.bs.js");

function touch_all() {
  EntityHistory.batchInsertRows();
  Promise.all();
  Promise.resolve();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
