// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Viem = require("viem");

function touch_all() {
  Viem.decodeEventLog();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
