// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Schema = require("envio/src/db/Schema.bs.js");
let Postgres = require("postgres");

function touch_all() {
  Postgres();
  Schema.make();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
