// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let ChainMap = require("envio/src/ChainMap.bs.js");

function touch_all() {
  ChainMap.get();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
