// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Rest = require("envio/src/vendored/Rest.bs.js");

function touch_all() {
  Rest.client();
  Rest.fetch();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
