// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Utils = require("envio/src/Utils.bs.js");

function touch_all() {
  Utils.unwrapResultExn();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
