// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function touch_all() {
  Promise.all();
  new Promise(undefined);
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
