// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Table = require("envio/src/db/Table.bs.js");
let Utils = require("envio/src/Utils.bs.js");
let Schema = require("envio/src/db/Schema.bs.js");

function touch_all() {
  Schema.getDerivedFromFieldName();
  Table.getDerivedFromFields();
  Table.getLinkedEntityFields();
  Utils.unwrapResultExn();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
