// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Table = require("envio/src/db/Table.bs.js");

function touch_all() {
  Promise.all();
  Table.getPrimaryKeyFieldNames();
  Table.toSqlParams();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
