// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Address = require("envio/src/Address.bs.js");

function touch_all() {
  Address.schema();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
