// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Table = require("envio/src/db/Table.bs.js");
let EntityHistory = require("envio/src/db/EntityHistory.bs.js");

function touch_all() {
  EntityHistory.batchInsertRows();
  EntityHistory.fromTable();
  EntityHistory.insertRow();
  EntityHistory.makeHistoryRowSchema();
  Table.mkField();
  Table.mkTable();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
