// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Postgres = require("envio/src/bindings/Postgres.bs.js");

function touch_all() {
  Postgres.sslOptionsSchema();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
