// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Rest = require("envio/src/vendored/Rest.bs.js");
let Viem = require("envio/src/bindings/Viem.bs.js");
let LazyLoader = require("envio/src/LazyLoader.bs.js");
let LogSelection = require("envio/src/LogSelection.bs.js");
let Stdlib_Promise = require("@rescript/runtime/lib/js/Stdlib_Promise.js");

function touch_all() {
  LazyLoader.get();
  LazyLoader.make();
  LogSelection.compressTopicSelections();
  Promise.all();
  Promise.all();
  Stdlib_Promise.$$catch();
  Promise.race();
  Promise.reject();
  Promise.resolve();
  Rest.client();
  Rest.fetch();
  Viem.parseLogOrThrow();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
