// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Rest = require("envio/src/vendored/Rest.bs.js");
let Stdlib_Promise = require("@rescript/runtime/lib/js/Stdlib_Promise.js");

function touch_all() {
  Stdlib_Promise.$$catch();
  Promise.resolve();
  Rest.client();
  Rest.fetch();
}

touch_all();

exports.touch_all = touch_all;
/*  Not a pure module */
